[[main]]
  name    = "AI Systems"
  pageRef = "ai"
  weight  = 10

[[main]]
  name    = "LLM / Agents"
  pageRef = "llm"
  weight  = 20

[[main]]
  name    = "DevOps"
  pageRef = "devops"
  weight  = 30

[[main]]
  name    = "Projects"
  pageRef = "projects"
  weight  = 40

[[main]]
  name    = "Search"
  weight  = 50

  [main.params]
    type = "search"

[[main]]
  name    = "Theme"
  weight  = 60

  [main.params]
    type = "theme-toggle"
