baseURL = "http://example.org/"
languageCode = "en-us"
title = "Bharat Khanna Tech Blog"
theme = "hugo-theme-stack"

[params]
  author = "Bharat Khanna"
  description = "Tech articles, AI, LLM, DevOps, and more."
  mainSections = ["ai", "llm", "devops", "vector-db", "case-studies"]
  favicon = "/favicon.ico"
  dateFormat = "2006-01-02"
  sidebar = true
  toc = true
  comments = false

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2
