
baseURL  = "https://bharatkhanna.dev/"
title    = "Bharat Khanna"
theme    = "hextra"

defaultContentLanguage = "en"
enableRobotsTXT        = true
enableEmoji            = true
buildDrafts            = false
buildFuture            = false

[params]
  copyright = "© 2025-2026 Bharat Khanna"

[taxonomies]
  category = "categories"
  tag      = "tags"

[outputs]
  home    = ["HTML", "RSS"]

[sitemap]
  changefreq = "weekly"
  priority   = 0.5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions.passthrough]
      enable = true
      [markup.goldmark.extensions.passthrough.delimiters]
        block = [['\\[', '\\]'], ['$$', '$$']]
        inline = [['\\(', '\\)']]
  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 4
  [markup.highlight]
    noClasses = false
    tabWidth  = 2
